### PR TITLE
Fixed types on the ms function

### PR DESCRIPTION
**Pull request by JWebCoder**

### CODE REVIEW

**Comment by kt3k** [comment]
Thank you for updating!

Most part looks good to me. I think we should format the code with `deno fmt` command.

**Comment by JWebCoder** [comment]
> Thank you for updating!
> 
> Most part looks good to me. I think we should format the code with `deno fmt` command.

Formated :)

**Review by kt3k — APPROVED** [review]
LGTM!

**Comment by kt3k** [comment]
@kevinkassimo 
The current source code, especially the test cases, are so obsolete. I think we need to merge this change.

**Comment by JWebCoder** [comment]
Hello, any updates on this? I would like to use this in another module. Thank you.

**Comment by TooTallNate** [comment]
Confirmed these changes fix the TypeScript compilation issues. Please merge 😃

**Review by kevinkassimo — APPROVED** [review]
LGTM

**Pull request merged**
